### ISSUE TITLE
Supply Chain Security Validation / CodeQL Scanning failing for cloud-projects

### ISSUE THREAD

**Issue by aucampia** [coopnorge/github-workflow-supply-chain-security-validation#35]
https://github.com/coopnorge/cloud-projects/runs/7107195424?check_suite_focus=true#step:6:65

```
Automatically detected languages: []
  Error: Did not detect any languages to analyze. Please update input in workflow or check that GitHub detects the correct languages in your repository.
  Error: Did not detect any languages to analyze. Please update input in workflow or check that GitHub detects the correct languages in your repository.
      at getLanguages (/home/runner/work/_actions/github/codeql-action/v2/lib/config-utils.js:422:15)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async getDefaultConfig (/home/runner/work/_actions/github/codeql-action/v2/lib/config-utils.js:4[67](https://github.com/coopnorge/cloud-projects/runs/7107195424?check_suite_focus=true#step:6:69):23)
      at async Object.initConfig (/home/runner/work/_actions/github/codeql-action/v2/lib/config-utils.js:786:18)
      at async initConfig (/home/runner/work/_actions/github/codeql-action/v2/lib/init.js:43:20)
      at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/init-action.js:96:18)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/init-action.js:153:9)
```

**Comment by aucampia** [comment]
I'm guessing this is fixed now as we no longer get errors there.
